name: Main CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  hello-world:
    name: Hello World
    runs-on: unbuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"

  build:
    uses: ansonlin1/stock-valuation-aws/.github/workflows/worflow-cdk-build.yml@main
