name: Main CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  prd-deploy:
    name: Deploy to prd
    runs-on: unbuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"
