name: Pull Request Verification

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/workflow-cdk-build.yml
