name: Pull Request Verification

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: ansonlin1/stock-valuation-aws/.github/workflows/worflow-cdk-build.yml@main
